name: update-data
on: 
  push:
  schedule:
    - cron: "0 19 * * *"

jobs:
  update-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Boilerplate
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      # Use Stefan's script to parse Google Sheet data

      - name: Generate data
        run: |
          source("scripts/load_data.R")
        shell: Rscript {0}

      - name: Commit data
        run: |
          git config --local user.email "tompluck@mail.com"
          git config --local user.name "ThomasPluck"
          git add --all
          git commit -am "Update data"
          git push 

      # Report is generated using data freshly pushed to the repository

      - name: Install TeX
        run: |
          sudo apt-get install texlive
          sudo apt-get install texlive-latex-extra

      - name: Generate report
        run: Rscript -e 'rmarkdown::render("scripts/idpd_report.Rmd", output_format = "pdf_document", output_file = "../irish-demographic-polling-datasets.pdf")'

      # Second push to commit new report

      - name: Commit results
        run: |
            git config --local user.email "tompluck@mail.com"
            git config --local user.name "ThomasPluck"
            git add --all
            git commit -am "Update report"
            git push 
